name: 02-workflow events

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * * *'
  workflow_dispatch:
    


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the the trigger
              run: echo "I have been triggered by a${{github.event_name}} event"
  