name: 03-Workflow runners

on: push

jobs:
  ubuntu-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on Ubuntu runner"
          echo "Runner OS : $RUNNER_OS"
