name: -4 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut code
              uses: actions/checkout@v4

            - name: Setup Code
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci